/*
<important_code_snippet_instructions>
Using Replit AI Integrations for Anthropic access.
For fast responses, use claude-haiku-4-5 model.
For complex reasoning, use claude-sonnet-4-5 model.
Supported models: claude-opus-4-5, claude-sonnet-4-5, claude-haiku-4-5, claude-opus-4-1
</important_code_snippet_instructions>
*/

// <important_do_not_delete>
const DEFAULT_MODEL_STR = "claude-sonnet-4-5";
const FAST_MODEL_STR = "claude-haiku-4-5";
// </important_do_not_delete>

import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({
  apiKey: process.env.AI_INTEGRATIONS_ANTHROPIC_API_KEY,
  baseURL: process.env.AI_INTEGRATIONS_ANTHROPIC_BASE_URL,
});

interface MinPaymentRule {
  fixedCents: number;
  percentageBps: number;
  includesInterest: boolean;
}

interface LenderRuleDiscoveryResult {
  lenderName: string;
  ruleDescription: string;
  minPaymentRule: MinPaymentRule;
  confidence: "high" | "medium" | "low";
}

export async function discoverLenderRule(
  lenderName: string,
  country: string
): Promise<LenderRuleDiscoveryResult> {
  const prompt = `You are a financial data researcher. Find the minimum payment calculation rule for "${lenderName}" in ${country}.

Minimum payment rules typically follow this format:
- Fixed amount (e.g., $25, £5)
- Percentage of balance (e.g., 2.5%, 3%)
- Some rules include interest in the percentage calculation (common in UK)
- Final minimum payment is usually: max(fixed amount, percentage of balance)

Research the specific rule for this lender and return ONLY a JSON object (no other text) in this exact format:
{
  "lenderName": "${lenderName}",
  "ruleDescription": "Clear description of the rule (e.g., 'Greater of 2.5% of balance or $25')",
  "minPaymentRule": {
    "fixedCents": <amount in cents, e.g., 2500 for $25>,
    "percentageBps": <percentage in basis points, e.g., 250 for 2.5%>,
    "includesInterest": <true if percentage includes interest, typically false>
  },
  "confidence": "<high|medium|low>"
}

If you cannot find the exact rule, use typical industry standards for that country:
- US credit cards: max($25, 1% of balance)
- UK credit cards: max(£5, 2.5% of balance + interest)
- Canada: max(CA$10, 3% of balance)
- Australia: max(AU$25, 2% of balance)

Return ONLY the JSON object.`;

  const message = await anthropic.messages.create({
    max_tokens: 1024,
    messages: [{ role: 'user', content: prompt }],
    model: DEFAULT_MODEL_STR,
  });

  const responseText = message.content[0].type === 'text' ? message.content[0].text : '';
  
  try {
    const result = JSON.parse(responseText);
    return result;
  } catch (error) {
    // Fallback to default rules if parsing fails
    const defaultRules: Record<string, MinPaymentRule> = {
      'US': { fixedCents: 2500, percentageBps: 100, includesInterest: false },
      'GB': { fixedCents: 500, percentageBps: 250, includesInterest: true },
      'CA': { fixedCents: 1000, percentageBps: 300, includesInterest: false },
      'AU': { fixedCents: 2500, percentageBps: 200, includesInterest: false },
    };

    const rule = defaultRules[country] || defaultRules['US'];
    return {
      lenderName,
      ruleDescription: `Default rule for ${country}: Greater of fixed amount or percentage of balance`,
      minPaymentRule: rule,
      confidence: "low",
    };
  }
}

export async function generatePlanExplanation(
  strategy: string,
  totalDebt: number,
  totalInterest: number,
  payoffMonths: number,
  accountCount: number
): Promise<string> {
  const prompt = `Generate a clear, concise explanation (2-3 paragraphs) for why this debt repayment plan works well.

Plan Details:
- Strategy: ${strategy}
- Total Debt: $${(totalDebt / 100).toFixed(2)}
- Total Interest: $${(totalInterest / 100).toFixed(2)}
- Payoff Time: ${payoffMonths} months
- Number of Accounts: ${accountCount}

The explanation should:
1. Explain how the chosen strategy benefits the user
2. Highlight the key advantages of this specific plan
3. Be encouraging and motivating without being overly optimistic
4. Use plain language for non-financial experts

Write the explanation as if speaking directly to the user ("you will", "your plan").`;

  const message = await anthropic.messages.create({
    max_tokens: 500,
    messages: [{ role: 'user', content: prompt }],
    model: DEFAULT_MODEL_STR,
  });

  return message.content[0].type === 'text' ? message.content[0].text : '';
}

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

export async function answerPlanQuestion(
  question: string,
  planData: any,
  initialExplanation: string,
  conversationHistory: ChatMessage[] = []
): Promise<string> {
  const systemPrompt = `You are an expert financial assistant. You are explaining a debt repayment plan generated by a separate, mathematical optimizer. You must not perform any calculations. Your only job is to explain the optimizer's logic using the data provided. Be clear, encouraging, and stick to the facts given.

The plan data includes month-by-month payment schedules showing:
- Which account receives payments each month
- Payment amounts, interest charged, and ending balances
- The total payoff timeline

Answer the user's question based solely on this data. Do not make up numbers or perform new calculations.

Initial Plan Explanation:
${initialExplanation || 'No initial explanation provided.'}

Plan Data Summary:
${Array.isArray(planData) ? 
  `The plan has ${planData.length} payment records across multiple months and accounts. Sample data: ${JSON.stringify(planData.slice(0, 10))}` :
  'No detailed plan data available.'}`;

  const messages: Array<{role: 'user' | 'assistant', content: string}> = [
    ...conversationHistory,
    { role: 'user', content: question }
  ];

  const message = await anthropic.messages.create({
    max_tokens: 1000,
    system: systemPrompt,
    messages,
    model: FAST_MODEL_STR,
  });

  return message.content[0].type === 'text' ? message.content[0].text : '';
}
