import { db } from "../db";
import { lenderProducts, type InsertLenderProduct } from "@shared/schema";

const ukLenderProducts: InsertLenderProduct[] = [
  // ==================== AMERICAN EXPRESS ====================
  {
    lenderName: "American Express",
    productName: "Platinum Card",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 2500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 65000,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest, or £25, whichever is higher",
    sourceUrl: "https://www.americanexpress.com/uk",
  },
  {
    lenderName: "American Express",
    productName: "Gold Card",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 2500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 19500,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest, or £25, whichever is higher",
    sourceUrl: "https://www.americanexpress.com/uk",
  },
  {
    lenderName: "American Express",
    productName: "BA Premium Plus",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 2500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 30000,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest, or £25, whichever is higher",
    sourceUrl: "https://www.americanexpress.com/uk",
  },
  {
    lenderName: "American Express",
    productName: "BA Credit Card (Free)",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 2500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £25, whichever is higher",
    sourceUrl: "https://www.americanexpress.com/uk",
  },
  {
    lenderName: "American Express",
    productName: "Cashback Everyday",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 2500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £25, whichever is higher",
    sourceUrl: "https://www.americanexpress.com/uk",
  },
  {
    lenderName: "American Express",
    productName: "Rewards Credit Card",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 2500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £25, whichever is higher",
    sourceUrl: "https://www.americanexpress.com/uk",
  },
  {
    lenderName: "American Express",
    productName: "Nectar Credit Card",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 2500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 3000,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest, or £25, whichever is higher",
    sourceUrl: "https://www.americanexpress.com/uk",
  },
  {
    lenderName: "American Express",
    productName: "Marriott Bonvoy",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 2500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 9500,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest, or £25, whichever is higher",
    sourceUrl: "https://www.americanexpress.com/uk",
  },

  // ==================== BARCLAYS / BARCLAYCARD ====================
  {
    lenderName: "Barclays",
    productName: "Avios Plus",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 24000,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest + fees, or £5, whichever is higher",
    sourceUrl: "https://www.barclays.co.uk/credit-cards",
  },
  {
    lenderName: "Barclays",
    productName: "Avios",
    country: "UK",
    purchaseAprBps: 2890,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest + fees, or £5, whichever is higher",
    sourceUrl: "https://www.barclays.co.uk/credit-cards",
  },
  {
    lenderName: "Barclays",
    productName: "Platinum",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest + fees, or £5, whichever is higher",
    sourceUrl: "https://www.barclays.co.uk/credit-cards",
  },
  {
    lenderName: "Barclays",
    productName: "Rewards",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest + fees, or £5, whichever is higher",
    sourceUrl: "https://www.barclays.co.uk/credit-cards",
  },
  {
    lenderName: "Barclays",
    productName: "Forward",
    country: "UK",
    purchaseAprBps: 3390,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest + fees, or £5, whichever is higher",
    sourceUrl: "https://www.barclays.co.uk/credit-cards",
  },

  // ==================== HSBC ====================
  {
    lenderName: "HSBC",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.hsbc.co.uk/credit-cards",
  },
  {
    lenderName: "HSBC",
    productName: "Purchase Plus",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.hsbc.co.uk/credit-cards",
  },
  {
    lenderName: "HSBC",
    productName: "Premier Credit Card",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.hsbc.co.uk/credit-cards",
  },

  // ==================== LLOYDS ====================
  {
    lenderName: "Lloyds",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.lloydsbank.com/credit-cards",
  },
  {
    lenderName: "Lloyds",
    productName: "Platinum Purchase",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.lloydsbank.com/credit-cards",
  },
  {
    lenderName: "Lloyds",
    productName: "Cashback",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.lloydsbank.com/credit-cards",
  },
  {
    lenderName: "Lloyds",
    productName: "Club Lloyds Platinum",
    country: "UK",
    purchaseAprBps: 2190,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.lloydsbank.com/credit-cards",
  },

  // ==================== HALIFAX ====================
  {
    lenderName: "Halifax",
    productName: "Clarity",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.halifax.co.uk/credit-cards",
  },
  {
    lenderName: "Halifax",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.halifax.co.uk/credit-cards",
  },
  {
    lenderName: "Halifax",
    productName: "Purchase Credit Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.halifax.co.uk/credit-cards",
  },
  {
    lenderName: "Halifax",
    productName: "Cashback Extras",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.halifax.co.uk/credit-cards",
  },

  // ==================== NATWEST ====================
  {
    lenderName: "NatWest",
    productName: "Reward Credit Card",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 2400,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.natwest.com/credit-cards",
  },
  {
    lenderName: "NatWest",
    productName: "Reward Black",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 8400,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.natwest.com/credit-cards",
  },
  {
    lenderName: "NatWest",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.natwest.com/credit-cards",
  },
  {
    lenderName: "NatWest",
    productName: "Purchase & Balance Transfer",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.natwest.com/credit-cards",
  },

  // ==================== SANTANDER ====================
  {
    lenderName: "Santander",
    productName: "All in One",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.santander.co.uk/credit-cards",
  },
  {
    lenderName: "Santander",
    productName: "Everyday",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.santander.co.uk/credit-cards",
  },
  {
    lenderName: "Santander",
    productName: "World Elite",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.santander.co.uk/credit-cards",
  },

  // ==================== NATIONWIDE ====================
  {
    lenderName: "Nationwide",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.nationwide.co.uk/credit-cards",
  },
  {
    lenderName: "Nationwide",
    productName: "Select",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.nationwide.co.uk/credit-cards",
  },
  {
    lenderName: "Nationwide",
    productName: "Purchase",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.nationwide.co.uk/credit-cards",
  },

  // ==================== TSB ====================
  {
    lenderName: "TSB",
    productName: "Balance Transfer Plus",
    country: "UK",
    purchaseAprBps: 2390,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.tsb.co.uk/credit-cards",
  },
  {
    lenderName: "TSB",
    productName: "Purchase Plus",
    country: "UK",
    purchaseAprBps: 2390,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.tsb.co.uk/credit-cards",
  },
  {
    lenderName: "TSB",
    productName: "Classic",
    country: "UK",
    purchaseAprBps: 2390,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.tsb.co.uk/credit-cards",
  },

  // ==================== VIRGIN MONEY ====================
  {
    lenderName: "Virgin Money",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://uk.virginmoney.com/credit-cards",
  },
  {
    lenderName: "Virgin Money",
    productName: "All Round",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://uk.virginmoney.com/credit-cards",
  },
  {
    lenderName: "Virgin Money",
    productName: "Virgin Atlantic Reward",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://uk.virginmoney.com/credit-cards",
  },
  {
    lenderName: "Virgin Money",
    productName: "Virgin Atlantic Reward+",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 16000,
    membershipFeeFrequency: "annual",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://uk.virginmoney.com/credit-cards",
  },

  // ==================== TESCO BANK ====================
  {
    lenderName: "Tesco Bank",
    productName: "Clubcard Credit Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.tescobank.com/credit-cards",
  },
  {
    lenderName: "Tesco Bank",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.tescobank.com/credit-cards",
  },
  {
    lenderName: "Tesco Bank",
    productName: "Foundation",
    country: "UK",
    purchaseAprBps: 2990,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.tescobank.com/credit-cards",
  },

  // ==================== SAINSBURY'S BANK ====================
  {
    lenderName: "Sainsbury's Bank",
    productName: "Nectar Credit Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.sainsburysbank.co.uk/credit-cards",
  },
  {
    lenderName: "Sainsbury's Bank",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.sainsburysbank.co.uk/credit-cards",
  },
  {
    lenderName: "Sainsbury's Bank",
    productName: "Dual Offer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.sainsburysbank.co.uk/credit-cards",
  },

  // ==================== M&S BANK ====================
  {
    lenderName: "M&S Bank",
    productName: "Rewards Credit Card",
    country: "UK",
    purchaseAprBps: 2390,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://bank.marksandspencer.com/credit-cards",
  },
  {
    lenderName: "M&S Bank",
    productName: "Transfer Plus",
    country: "UK",
    purchaseAprBps: 2390,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://bank.marksandspencer.com/credit-cards",
  },
  {
    lenderName: "M&S Bank",
    productName: "Shopping Plus",
    country: "UK",
    purchaseAprBps: 2390,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://bank.marksandspencer.com/credit-cards",
  },

  // ==================== CAPITAL ONE ====================
  {
    lenderName: "Capital One",
    productName: "Classic",
    country: "UK",
    purchaseAprBps: 3490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 300,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "3% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.capitalone.co.uk/credit-cards",
  },
  {
    lenderName: "Capital One",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 300,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "3% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.capitalone.co.uk/credit-cards",
  },

  // ==================== VANQUIS ====================
  {
    lenderName: "Vanquis",
    productName: "Classic",
    country: "UK",
    purchaseAprBps: 3990,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 300,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "3% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.vanquis.co.uk/credit-cards",
  },
  {
    lenderName: "Vanquis",
    productName: "Chrome",
    country: "UK",
    purchaseAprBps: 3990,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 300,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "3% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.vanquis.co.uk/credit-cards",
  },
  {
    lenderName: "Vanquis",
    productName: "Origin",
    country: "UK",
    purchaseAprBps: 3490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 300,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "3% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.vanquis.co.uk/credit-cards",
  },

  // ==================== AQUA ====================
  {
    lenderName: "Aqua",
    productName: "Classic",
    country: "UK",
    purchaseAprBps: 3490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 300,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "3% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.aquacard.co.uk",
  },
  {
    lenderName: "Aqua",
    productName: "Reward",
    country: "UK",
    purchaseAprBps: 3490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 300,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "3% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.aquacard.co.uk",
  },
  {
    lenderName: "Aqua",
    productName: "Advance",
    country: "UK",
    purchaseAprBps: 2990,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 300,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "3% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.aquacard.co.uk",
  },

  // ==================== ZOPA ====================
  {
    lenderName: "Zopa",
    productName: "Credit Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.zopa.com/credit-cards",
  },

  // ==================== MONZO ====================
  {
    lenderName: "Monzo",
    productName: "Credit Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://monzo.com/credit",
  },

  // ==================== CHASE ====================
  {
    lenderName: "Chase",
    productName: "Credit Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.chase.co.uk",
  },

  // ==================== FIRST DIRECT ====================
  {
    lenderName: "First Direct",
    productName: "Credit Card",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www1.firstdirect.com/credit-cards",
  },

  // ==================== JOHN LEWIS ====================
  {
    lenderName: "John Lewis",
    productName: "Partnership Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.johnlewis.com/our-services/john-lewis-partnership-card",
  },

  // ==================== POST OFFICE ====================
  {
    lenderName: "Post Office",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.postoffice.co.uk/credit-cards",
  },
  {
    lenderName: "Post Office",
    productName: "Purchase",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.postoffice.co.uk/credit-cards",
  },

  // ==================== ASDA MONEY ====================
  {
    lenderName: "Asda Money",
    productName: "Cashback Credit Card",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://money.asda.com/credit-cards",
  },

  // ==================== METRO BANK ====================
  {
    lenderName: "Metro Bank",
    productName: "Credit Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.metrobankonline.co.uk/credit-cards",
  },

  // ==================== STARLING ====================
  {
    lenderName: "Starling",
    productName: "Credit Card",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.starlingbank.com",
  },

  // ==================== AA ====================
  {
    lenderName: "AA",
    productName: "Credit Card",
    country: "UK",
    purchaseAprBps: 2290,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.theaa.com/credit-cards",
  },

  // ==================== CO-OPERATIVE BANK ====================
  {
    lenderName: "Co-operative Bank",
    productName: "Credit Card",
    country: "UK",
    purchaseAprBps: 2390,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.co-operativebank.co.uk/credit-cards",
  },

  // ==================== MBNA ====================
  {
    lenderName: "MBNA",
    productName: "Balance Transfer",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.mbna.co.uk/credit-cards",
  },
  {
    lenderName: "MBNA",
    productName: "Purchase",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.mbna.co.uk/credit-cards",
  },
  {
    lenderName: "MBNA",
    productName: "All Rounder",
    country: "UK",
    purchaseAprBps: 2490,
    minPaymentFixedCents: 500,
    minPaymentPercentageBps: 250,
    minPaymentIncludesInterest: true,
    membershipFeeCents: 0,
    membershipFeeFrequency: "none",
    ruleDescription: "2.5% of balance + interest, or £5, whichever is higher",
    sourceUrl: "https://www.mbna.co.uk/credit-cards",
  },
];

export async function seedLenderProductsData() {
  console.log("Seeding UK lender products...");
  
  for (const product of ukLenderProducts) {
    try {
      await db.insert(lenderProducts).values(product).onConflictDoNothing();
      console.log(`  + ${product.lenderName} - ${product.productName}`);
    } catch (error) {
      console.error(`  ! Failed to insert ${product.lenderName} - ${product.productName}:`, error);
    }
  }
  
  console.log(`\nSeeded ${ukLenderProducts.length} products from ${new Set(ukLenderProducts.map(p => p.lenderName)).size} lenders.`);
}

